# This is the default configuration file. Enabling and disabling is configured
# in separate files. This file adds all other parameters apart from Enabled.

# Common configuration.
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - lib/aspose_words_cloud/api_client.rb
Metrics/LineLength:
  Max: 7010
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Metrics/ClassLength:
  Max: 10000
Metrics/MethodLength:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 60
Metrics/AbcSize:
  Max: 350
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
Style/IfUnlessModifier:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/SymbolLiteral:
  Enabled: false
Lint:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/LeadingBlankLines:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/Tab:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false