=begin
#Aspose.Words for Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 17.12

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'date'

module SwaggerClient
  # Class for document replace text request building.
  class ReplaceTextRequest
    # Old text value (or regex pattern ) to replace.
    attr_accessor :old_value

    # New text value to replace by.
    attr_accessor :new_value

    # Flag, true means the search is case-sensitive; false means the search is not case-sensitive.
    attr_accessor :is_match_case

    # Flag, means that only whole word matched are replaced.
    attr_accessor :is_match_whole_word

    # Flag, means that  contains regex expression.
    attr_accessor :is_old_value_regex


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'old_value' => :'OldValue',
        :'new_value' => :'NewValue',
        :'is_match_case' => :'IsMatchCase',
        :'is_match_whole_word' => :'IsMatchWholeWord',
        :'is_old_value_regex' => :'IsOldValueRegex'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'old_value' => :'String',
        :'new_value' => :'String',
        :'is_match_case' => :'BOOLEAN',
        :'is_match_whole_word' => :'BOOLEAN',
        :'is_old_value_regex' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'OldValue')
        self.old_value = attributes[:'OldValue']
      end

      if attributes.has_key?(:'NewValue')
        self.new_value = attributes[:'NewValue']
      end

      if attributes.has_key?(:'IsMatchCase')
        self.is_match_case = attributes[:'IsMatchCase']
      end

      if attributes.has_key?(:'IsMatchWholeWord')
        self.is_match_whole_word = attributes[:'IsMatchWholeWord']
      end

      if attributes.has_key?(:'IsOldValueRegex')
        self.is_old_value_regex = attributes[:'IsOldValueRegex']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @is_match_case.nil?
        invalid_properties.push("invalid value for 'is_match_case', is_match_case cannot be nil.")
      end

      if @is_match_whole_word.nil?
        invalid_properties.push("invalid value for 'is_match_whole_word', is_match_whole_word cannot be nil.")
      end

      if @is_old_value_regex.nil?
        invalid_properties.push("invalid value for 'is_old_value_regex', is_old_value_regex cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @is_match_case.nil?
      return false if @is_match_whole_word.nil?
      return false if @is_old_value_regex.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          old_value == o.old_value &&
          new_value == o.new_value &&
          is_match_case == o.is_match_case &&
          is_match_whole_word == o.is_match_whole_word &&
          is_old_value_regex == o.is_old_value_regex
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [old_value, new_value, is_match_case, is_match_whole_word, is_old_value_regex].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
